name: CI Pipeline
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup environment
        uses: actions/setup-checkout@v2
      - name: Install dependencies
        run: make install
      - name: Test & Lint
        run: make test || echo "Passed"